import 'package:flutter/material.dart';

Map<String, List<IconData>> icons = {
  "Actions": [
    Icons.abc,
    Icons.threed_rotation,
    Icons.account_balance,
    Icons.account_balance_wallet,
    Icons.account_box,
    Icons.alarm,
    Icons.analytics,
    Icons.android,
    Icons.article,
    Icons.assessment,
    Icons.assignment,
    Icons.book,
    Icons.build,
    Icons.calendar_month,
    Icons.calendar_today,
    Icons.code,
    Icons.credit_card,
    Icons.delete,
    Icons.delete_forever,
    Icons.event,
    Icons.extension,
    Icons.extension_off,
    Icons.group_work,
    Icons.home,
    Icons.info,
    Icons.receipt,
    Icons.request_page,
    Icons.savings,
    Icons.shopping_bag,
    Icons.shopping_basket,
    Icons.shopping_cart,
    Icons.theaters,
    Icons.work,
  ],
  "Audio \\ Video": [
    Icons.mic,
    Icons.movie,
    Icons.subscriptions,
  ],
  "Communication": [
    Icons.business,
    Icons.call,
  ],
  "Hardware": [
    Icons.computer,
    Icons.desktop_mac,
    Icons.desktop_windows,
    Icons.gamepad,
    Icons.headphones,
    Icons.keyboard,
    Icons.monitor,
    Icons.mouse,
    Icons.tablet,
    Icons.tv,
  ],
  "Search": [
    Icons.bed,
    Icons.blender,
    Icons.chair,
    Icons.coffee,
    Icons.dining,
    Icons.flatware,
  ],
  "Food": [
    Icons.breakfast_dining,
    Icons.brunch_dining,
    Icons.cake,
    Icons.egg,
    Icons.fastfood,
    Icons.icecream,
    Icons.kitchen,
    Icons.liquor,
    Icons.local_bar,
    Icons.local_dining,
    Icons.local_pizza,
    Icons.lunch_dining,
    Icons.ramen_dining,
    Icons.restaurant,
    Icons.restaurant_menu,
    Icons.soup_kitchen,
  ],
  "Travel": [
    Icons.drive_eta,
    Icons.electric_bike,
    Icons.electric_car,
    Icons.electric_moped,
    Icons.flight,
    Icons.hiking,
    Icons.hotel,
    Icons.snowmobile,
    Icons.subway,
    Icons.two_wheeler,
    Icons.villa,
  ],
};
